### ISSUE TITLE
Measurable Decomm: replacements apps

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#4693]

**Comment by davidwatkins73** [comment]
**Todo**

- [ ] Security check on endpoint
- [ ] Logging
- [ ] migrator ('new')
- [ ] add/remove replacements
- [ ] edit replacement comm date
